#1. Charlie has a magic mirror which shows the right rotated versions of a given word . The right rotated version of a word is generated by writing the word in a circle of clockwise order . It can be read clockwise from any character given until all the characters are covered . eg; in the word "sample" if we start with 'p'we get the right rotated word as "plesam"

#check if rotated_string is the rotated string of original_string


# The first line of the input consists of a string - word1 representing the first word. the second line consists of a string word2, a string representing the second word

original_str = input('Enter the original string: ')  # kerala
rotated_str = input('Enter the rotated string: ')    #alaker
 
temp_str = rotated_str * 2                           #alakeralaker - here we found the original string
if temp_str.find(original_str) != -1:
    print(f'{rotated_str} is rotated string of {original_str}')
else:
    print(f'{rotated_str} is Not rotated string of {original_str}')


